<?php
declare(strict_types=1);
session_name('googa');session_start();
require_once __DIR__.'/lib/store.php';require_once __DIR__.'/lib/version.php';require_once __DIR__.'/lib/ambassador.php';
$context=googa_session_context();googa_require_parent($context);$data=googa_load_data();$email=googa_normalize_email((string)($context['email']??''));
$user=$data['users'][$email]??[];$eligible=googa_ambassador_user_eligible($user);$application=null;$storageError='';
try{$application=googa_ambassador_find_for_email($email);}catch(Throwable $e){$storageError='Søknadsløsningen er ikke ferdig konfigurert.';}
if(empty($_SESSION['googa_csrf']))$_SESSION['googa_csrf']=bin2hex(random_bytes(16));$message='';$ok=false;
if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!hash_equals((string)$_SESSION['googa_csrf'],(string)($_POST['csrf']??''))){http_response_code(400);exit('Ugyldig forespørsel.');}
  try{$created=googa_ambassador_create_application($user,(string)($_POST['name']??''),(string)($_POST['identity']??''),(string)($_POST['email']??''));$sent=googa_send_ambassador_signing_email($created['application'],$created['token']);googa_ambassador_store_transaction(function(array &$store)use($created,$sent){$id=$created['application']['id'];$store['applications'][$id]['email_sent']=$sent;$store['applications'][$id]['events'][]=['type'=>$sent?'email_sent':'email_failed','at'=>googa_now()];});if(!$sent)throw new RuntimeException('Søknaden er lagret, men e-posten kunne ikke sendes. Kontakt Sandra.');$application=$created['application'];$application['email_sent']=true;$message='Avtalen er sendt til e-postadressen din.';$ok=true;}catch(Throwable $e){$message=$e->getMessage();}
}
$statusLabels=['sent'=>'Sendt til signering','viewed'=>'Åpnet – venter på signatur','signed'=>'Signert – aktiveres automatisk','activating'=>'Automatisk aktivering pågår','activation_pending'=>'Signert – automatisk aktivering prøves igjen','active'=>'Aktiv','approved'=>'Aktiv','rejected'=>'Ikke godkjent'];
?><!doctype html><html lang="so"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#103654"><title>Googa – safiir</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@700;800&family=Nunito:wght@600;700;800;900&display=swap" rel="stylesheet"><style>
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 90% 0,#bfeff0 0,transparent 38%),linear-gradient(145deg,#fff7d8,#effbfa);font-family:Nunito,system-ui;color:#123b59}.shell{width:min(920px,100%);margin:auto;padding:14px 14px 48px}.top{display:flex;justify-content:space-between;align-items:center}.top a{color:#123b59;font-weight:900;text-decoration:none}.lang{width:46px;height:46px;border:0;border-radius:15px;background:#fff;box-shadow:0 7px 20px #1036541c;font-size:20px}.hero,.terms,.apply{background:#fffdf7;border:1px solid #fff;border-radius:28px;box-shadow:0 18px 44px #10365418}.hero{display:grid;grid-template-columns:1fr 170px;gap:20px;padding:30px;margin:14px 0}.hero h1{margin:6px 0;font:800 clamp(40px,7vw,62px)/.95 'Baloo 2'}.hero p{line-height:1.55;color:#557084}.hero img{width:155px;align-self:end}.eyebrow{font-size:12px;font-weight:900;letter-spacing:.12em;color:#087f89}.benefits{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px}.benefits span{padding:14px;border-radius:18px;background:#e8f7f8;font-weight:900}.terms,.apply{padding:25px;margin-top:14px}.terms h2,.apply h2{font:800 30px 'Baloo 2';margin:0 0 8px}.terms details{border-top:1px solid #dce8e8;padding:13px 0}.terms summary{font-weight:900;cursor:pointer}.terms p,.apply p{color:#557084;line-height:1.55}.notice{padding:13px 15px;border-radius:15px;background:#fff1bd;font-weight:800}.notice.ok{background:#dff6e9;color:#176648}.field{display:grid;gap:6px;margin:12px 0}.field label{font-weight:900}.field input{width:100%;min-height:50px;border:2px solid #d7e3e8;border-radius:14px;padding:10px 13px;font:inherit;background:white}.field small{color:#667d8e}.check{display:flex;gap:10px;align-items:flex-start;margin:15px 0;color:#405d73}.check input{width:20px;height:20px;flex:0 0 auto}.cta{min-height:52px;border:0;border-radius:15px;background:#087f89;color:white;padding:12px 20px;font:900 17px Nunito;cursor:pointer}.cta[disabled]{background:#9baeb7;cursor:not-allowed}.status{display:grid;gap:7px;padding:18px;border-radius:20px;background:linear-gradient(135deg,#123b59,#087f89);color:white}.status strong{font:800 25px 'Baloo 2'}.legal{font-size:12px;color:#6c8190;margin-top:14px}@media(max-width:650px){.hero{grid-template-columns:1fr;padding:22px}.hero img{position:absolute;width:86px;right:22px;top:75px;opacity:.25}.benefits{grid-template-columns:1fr}.terms,.apply{padding:20px;border-radius:23px}}
</style></head><body><main class="shell"><div class="top"><a href="help.php">← <span data-so="Caawimo" data-no="Hjelp">Caawimo</span></a><button class="lang" id="lang" type="button">🇳🇴</button></div><section class="hero"><div><div class="eyebrow" data-so="SAFIIRKA GOOGA" data-no="GOOGA-AMBASSADØR">SAFIIRKA GOOGA</div><h1 data-so="La wadaag Googa. Labadiinuba faa'iida." data-no="Del Googa. Begge får noe igjen.">La wadaag Googa. Labadiinuba faa'iida.</h1><p data-so="Sida macmiil dhab ah, waxaad qoysaska kale kula talin kartaa Googa. Iyagu waxay helaan qiimo-dhimis, adiguna waxaad heshaa komishan iibka qoysaska gaarka ah." data-no="Som reell kunde kan du anbefale Googa til andre familier. De får rabatt, og du opptjener provisjon på direkte salg til private familier.">Sida macmiil dhab ah, waxaad qoysaska kale kula talin kartaa Googa.</p><div class="benefits"><span data-so="Qoyska: kr 50 faa'iido" data-no="Familien: kr 50 fordel">Qoyska: kr 50 faa'iido</span><span data-so="Adiga: 20% ilaa 12 bilood" data-no="Du: 20 % i opptil 12 måneder">Adiga: 20% ilaa 12 bilood</span><span data-so="Xisaab cad oo fudud" data-no="Enkel og sporbar avregning">Xisaab cad oo fudud</span></div></div><img src="<?=htmlspecialchars(googa_asset_url('assets/googa-mascot-key.png'),ENT_QUOTES,'UTF-8')?>" alt=""></section>
<?php if($message!==''):?><p class="notice<?=$ok?' ok':''?>"><?=htmlspecialchars($message,ENT_QUOTES,'UTF-8')?></p><?php endif;?>
<section class="terms"><h2 data-so="Sida ay u shaqeyso" data-no="Slik fungerer det">Sida ay u shaqeyso</h2><p data-so="Akhri qodobada kooban. Heshiiska buuxa ee Noorwiijiga ah wuxuu kuugu imanayaa PDF ka hor saxiixa." data-no="Les kortvilkårene. Den fullstendige norske avtalen kommer som PDF før du signerer.">Akhri qodobada kooban.</p>
<details open><summary data-so="Yaa noqon kara safiir?" data-no="Hvem kan bli ambassadør?">Yaa noqon kara safiir?</summary><p data-so="Waa inaad 18 jir tahay, macmiil lacag bixiya ahaataa, oo aad Googa haysatay ugu yaraan 30 maalmood." data-no="Du må være 18 år, betalende kunde og ha hatt Googa i minst 30 dager.">Waa inaad 18 jir tahay, macmiil lacag bixiya ahaataa.</p></details>
<details><summary data-so="Maxaa komishan laga bixiyaa?" data-no="Hva gir provisjon?">Maxaa komishan laga bixiyaa?</summary><p data-so="Keliya rukhsadaha bilaha ama sanadlaha ah ee qoys cusub oo gaar loo leeyahay uu toos uga iibsado Googa isagoo isticmaalaya koodhkaaga." data-no="Bare nye måneds- eller årsabonnement som private familier kjøper direkte fra Googa med koden din.">Keliya rukhsadaha qoysaska gaarka ah.</p></details>
<details><summary data-so="Maxaa aan komishan laga bixin?" data-no="Hva er ikke med?">Maxaa aan komishan laga bixin?</summary><p data-so="Ururro, jaaliyado, iskuullo, maktabado, degmooyin, shirkado, hadiyado, Ordreise, wax-iibsiyo dheeraad ah iyo kr 5-ka bilowga ah kuma jiraan." data-no="Forenings- og organisasjonspakker, skoler, bibliotek, kommuner, virksomheter, gaver, Ordreise, tilleggskjøp og introduksjonsbeløpet på kr 5 er uttrykkelig unntatt.">Ururrada iyo wax-iibsiyada kale kuma jiraan.</p></details>
<details><summary data-so="Goorma ayaa la bixiyaa?" data-no="Når utbetales det?">Goorma ayaa la bixiyaa?</summary><p data-so="Komishanku 30 maalmood ayuu sugayaa, kadibna caadi ahaan saddexdii biloodba mar ayaa gacanta lagu xisaabiyaa. Lacag celin iyo lacag diidmo waa laga jarayaa." data-no="Hver provisjonspost holdes i 30 dager og avregnes normalt kvartalsvis. Refusjoner og chargebacks trekkes fra.">Komishanku 30 maalmood ayuu sugayaa.</p></details>
<details><summary data-so="Sidee loo xayeysiinayaa?" data-no="Hvordan kan du markedsføre?">Sidee loo xayeysiinayaa?</summary><p data-so="Si cad ugu qor «xayeysiis» marka aad faa'iido ka heli karto. Ha ballanqaadin wax aan Googa sheegin, hana iska dhigin shaqaale Googa." data-no="Merk tydelig som reklame når du kan få provisjon. Oppgi riktige priser og vilkår, og ikke fremstå som ansatt eller talsperson for Googa.">Si cad ugu qor xayeysiis.</p></details></section>
<section class="apply" id="apply"><h2 data-so="Codso laba daqiiqo gudahood" data-no="Søk på to minutter">Codso laba daqiiqo gudahood</h2>
<?php if(is_array($application)&&in_array((string)$application['status'],['sent','viewed','signed','activating','activation_pending','active','approved'],true)):?><div class="status"><small data-so="XAALADDA CODSIGA" data-no="STATUS FOR SØKNADEN">XAALADDA CODSIGA</small><strong><?=htmlspecialchars($statusLabels[$application['status']]??$application['status'],ENT_QUOTES,'UTF-8')?></strong><span><?=htmlspecialchars((string)$application['email'],ENT_QUOTES,'UTF-8')?></span><?php if(!empty($application['ambassador_code'])):?><b><?=htmlspecialchars((string)$application['ambassador_code'],ENT_QUOTES,'UTF-8')?></b><?php endif;?></div>
<?php elseif($storageError!==''):?><p class="notice"><?=htmlspecialchars($storageError,ENT_QUOTES,'UTF-8')?></p>
<?php else:?><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars((string)$_SESSION['googa_csrf'],ENT_QUOTES,'UTF-8')?>"><div class="field"><label for="name" data-so="Magaca oo buuxa" data-no="Fullt navn">Magaca oo buuxa</label><input id="name" name="name" autocomplete="name" maxlength="120" value="<?=htmlspecialchars((string)($user['name']??''),ENT_QUOTES,'UTF-8')?>" required></div><div class="field"><label for="identity" data-so="Lambarka dhalashada / aqoonsiga dowladda" data-no="Fødselsnummer / offentlig ID-nummer">Lambarka dhalashada / aqoonsiga dowladda</label><input id="identity" name="identity" autocomplete="off" inputmode="text" minlength="6" maxlength="30" required><small data-so="Si sir ah ayaa loo kaydiyaa, mana geli doono Stripe, e-mail ama diiwaanka caadiga ah." data-no="Krypteres og lagres utenfor webroten. Det legges ikke i Stripe, e-post eller vanlig Googa-logg.">Si sir ah ayaa loo kaydiyaa.</small></div><div class="field"><label for="email">E-mail</label><input id="email" name="email" type="email" autocomplete="email" value="<?=htmlspecialchars($email,ENT_QUOTES,'UTF-8')?>" required></div><label class="check"><input type="checkbox" required><span data-so="Waxaan fahmay in xogtan loo isticmaalo codsiga, aqoonsiga iyo heshiiska safiirnimada." data-no="Jeg forstår at opplysningene brukes til søknaden, identitetskontroll og ambassadøravtalen.">Waxaan fahmay sida xogta loo isticmaalo.</span></label><button class="cta" type="submit"<?=$eligible?'':' disabled'?> data-so="Ii soo dir heshiiska" data-no="Send meg avtalen">Ii soo dir heshiiska</button><?php if(!$eligible):?><p class="notice" data-so="Waxaad codsan kartaa marka aad 30 maalmood ahayd macmiil lacag bixiya." data-no="Du kan søke når du har vært betalende kunde i 30 dager.">Waxaad codsan kartaa marka aad 30 maalmood ahayd macmiil lacag bixiya.</p><?php endif;?></form><?php endif;?><p class="legal" data-so="Saxiixa elektaroonigga ahi waa saxiix fudud, mana aha BankID. Marka saxiixa iyo hubinta otomaatiga ahi dhammaadaan, heshiiska iyo koodhku si toos ah ayay u shaqaynayaan." data-no="Signeringen er en enkel elektronisk signatur, ikke BankID. Når signeringen og den automatiske kontrollen er fullført, trer avtalen i kraft og koden aktiveres uten manuelle steg.">Saxiixa iyo hubinta kadib koodhku si toos ah ayuu u shaqaynayaa.</p></section></main><script>let l='so';document.getElementById('lang').onclick=()=>{l=l==='so'?'no':'so';document.documentElement.lang=l;document.getElementById('lang').textContent=l==='so'?'🇳🇴':'🇸🇴';document.querySelectorAll('[data-so]').forEach(e=>e.textContent=e.dataset[l])}</script></body></html>
