<?php
declare(strict_types=1);
require_once __DIR__.'/lib/ambassador.php';
header('Cache-Control: no-store, private, max-age=0');header('Referrer-Policy: no-referrer');header('X-Robots-Tag: noindex, nofollow');
if($_SERVER['REQUEST_METHOD']==='POST'){
  header('Content-Type: application/json; charset=utf-8');
  try{$body=json_decode((string)file_get_contents('php://input'),true,16,JSON_THROW_ON_ERROR);$action=(string)($body['action']??'');$token=(string)($body['token']??'');if($action==='open')$result=['ok'=>true,'application'=>googa_ambassador_open($token)];elseif($action==='sign')$result=['ok'=>true,'application'=>googa_ambassador_sign($token,(string)($body['name']??''),(bool)($body['accepted']??false),(bool)($body['adult']??false))];elseif($action==='pdf'){header_remove('Content-Type');header('Content-Type: application/pdf');header('Content-Disposition: inline; filename="Googa-ambassadoravtale.pdf"');echo googa_ambassador_pdf_for_token($token);exit;}else throw new RuntimeException('Ugyldig handling.');echo json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}catch(Throwable $e){http_response_code(400);echo json_encode(['ok'=>false,'error'=>$e->getMessage()],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);}exit;
}
?><!doctype html><html lang="no"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#103654"><meta name="robots" content="noindex,nofollow"><title>Signer Googa-avtale</title><style>*{box-sizing:border-box}body{margin:0;background:linear-gradient(145deg,#e8f7f8,#fff6d5);font:16px/1.5 system-ui;color:#103654}.shell{width:min(780px,100%);margin:auto;padding:18px}.card{background:#fffdf7;border-radius:24px;padding:clamp(20px,5vw,34px);box-shadow:0 18px 45px #1036541c}.brand{font-weight:900;color:#087f89;letter-spacing:.12em}.loading{text-align:center;padding:50px}.hash{font:11px/1.4 monospace;overflow-wrap:anywhere;background:#edf5f4;padding:10px;border-radius:10px}.clauses{max-height:45vh;overflow:auto;border:1px solid #d7e4e6;border-radius:16px;padding:4px 16px;margin:18px 0;background:#fff}.clauses h3{font-size:16px;margin:16px 0 4px}.clauses p{margin:0 0 15px;color:#4c667a}.field{display:grid;gap:6px;margin:14px 0}.field input[type=text]{min-height:50px;border:2px solid #d1e0e5;border-radius:13px;padding:10px;font:inherit}.check{display:flex;gap:10px;margin:13px 0}.check input{width:21px;height:21px;flex:0 0 auto}.actions{display:flex;gap:10px;flex-wrap:wrap}.btn{border:0;border-radius:13px;background:#087f89;color:#fff;min-height:50px;padding:11px 18px;font-weight:900;cursor:pointer}.btn.alt{background:#e5f3f2;color:#103654}.btn:disabled{opacity:.55}.message{padding:13px;border-radius:13px;background:#fff0bc;font-weight:800}.done{padding:18px;border-radius:18px;background:#def6e8;color:#176648}@media(max-width:560px){.shell{padding:8px}.card{border-radius:20px}.clauses{max-height:40vh}.actions{display:grid}.btn{width:100%}}</style></head><body><main class="shell"><section class="card"><div class="brand">GOOGA · ELEKTRONISK SIGNERING</div><div id="loading" class="loading">Henter den frosne avtalen …</div><div id="content" hidden><h1 id="title"></h1><p id="meta"></p><p class="hash" id="hash"></p><div class="clauses" id="clauses"></div><form id="form"><div class="field"><label for="name"><b>Skriv fullt navn som elektronisk signatur</b></label><input id="name" type="text" autocomplete="name" maxlength="120" required></div><label class="check"><input id="accepted" type="checkbox" required><span>Jeg har lest PDF-en og teksten over, og godtar hele avtalen.</span></label><label class="check"><input id="adult" type="checkbox" required><span>Jeg bekrefter at jeg er minst 18 år og signerer på egne vegne.</span></label><div class="actions"><button class="btn alt" id="pdf" type="button">Åpne avtalen som PDF</button><button class="btn" id="sign" type="submit">Signer avtalen</button></div></form><p id="message" class="message" hidden></p></div></section></main><script>
const token=new URLSearchParams(location.hash.slice(1)).get('t')||'';history.replaceState(null,'',location.pathname);const loading=document.getElementById('loading'),content=document.getElementById('content'),message=document.getElementById('message');
async function call(action,extra={}){const response=await fetch(location.pathname,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'omit',body:JSON.stringify({action,token,...extra})});const type=response.headers.get('content-type')||'';if(type.includes('application/pdf'))return response.blob();const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Noe gikk galt.');return data;}
function render(a){loading.hidden=true;content.hidden=false;document.getElementById('title').textContent=a.document.title;document.getElementById('meta').textContent=`Avtale ${a.document.version} · ${a.name} · ${a.email}`;document.getElementById('hash').textContent='SHA-256 '+a.document_hash;document.getElementById('name').value=a.signed_name||a.name;document.getElementById('clauses').innerHTML=a.document.clauses.map(c=>`<section><h3>${escapeHtml(c.title)}</h3><p>${escapeHtml(c.text)}</p></section>`).join('');if(['signed','activating','activation_pending','active','approved'].includes(a.status)){const active=['active','approved'].includes(a.status);document.getElementById('form').innerHTML=`<div class="done"><b>${active?'Avtalen er aktiv.':'Avtalen er signert.'}</b><br>${escapeHtml(a.signed_at||'')}<br>${active?`Ambassadørkoden <b>${escapeHtml(a.ambassador_code||'')}</b> er aktiv. Du får også koden på e-post.`:'Signaturen er gyldig. Automatisk aktivering behandles nå og prøves igjen uten at du trenger å gjøre noe.'}</div>`;}}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function bindPdf(){document.getElementById('pdf')?.addEventListener('click',async()=>{try{const blob=await call('pdf');open(URL.createObjectURL(blob),'_blank','noopener')}catch(e){show(e.message)}})}function show(text){message.hidden=false;message.textContent=text}
if(!token){loading.textContent='Signeringslenken mangler eller er åpnet på feil måte.'}else call('open').then(d=>{render(d.application);bindPdf()}).catch(e=>loading.textContent=e.message);
document.getElementById('form')?.addEventListener('submit',async e=>{e.preventDefault();const button=document.getElementById('sign');button.disabled=true;try{const d=await call('sign',{name:document.getElementById('name').value,accepted:document.getElementById('accepted').checked,adult:document.getElementById('adult').checked});render(d.application)}catch(err){show(err.message);button.disabled=false}});
</script></body></html>
