(() => {
  const test=window.GOOGA_CULTURE_TEST,$=id=>document.getElementById(id);
  const savedVoice=localStorage.getItem('googa-culture-voice');
  const state={index:0,answers:[],norwegian:false,voice:savedVoice==='muuse'?'muuse':'ubax',result:null};
  window.GOOGA_AUDIO_PATH_RESOLVER=path=>!path||state.voice!=='muuse'||!path.startsWith('audio/culture-test/')?path:path.replace('audio/culture-test/','audio/culture-test/muuse/');
  const localized=(so,no)=>state.norwegian?no:so;
  const show=id=>['cultureIntro','cultureQuestion','cultureResult'].forEach(name=>$(name).classList.toggle('hidden',name!==id));
  const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const playButton=(button,text,audio='')=>{button.innerHTML=window.GoogaReadAloud.icon;button.onclick=event=>{event.preventDefault();event.stopPropagation();window.GoogaReadAloud.play(text,audio,button)}};
  const shareUrl=()=>new URL('culture-test.php',location.href).href;
  const shareCopy=()=>state.norwegian
    ? `Jeg fikk utmerkelsen «${state.result.profile.no}» i Bariis på Grandis?! Hva får du?`
    : `Waxaan helay biladda «${state.result.profile.so}» ee Bariis på Grandis?! Adigu maxaad heli doontaa?`;
  const channelLinks=()=>({
    facebook:`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl())}`,
    email:`mailto:?subject=${encodeURIComponent('Bariis på Grandis?!')}&body=${encodeURIComponent(`${shareCopy()}\n\n${shareUrl()}`)}`,
    message:`sms:${/iPad|iPhone|iPod/.test(navigator.userAgent)?'&':'?'}body=${encodeURIComponent(`${shareCopy()} ${shareUrl()}`)}`
  });
  const shareFeedback=message=>{$('cultureShareFeedback').textContent=message;window.clearTimeout(shareFeedback.timer);shareFeedback.timer=window.setTimeout(()=>{$('cultureShareFeedback').textContent=''},3500)};

  function updateLanguage(){
    document.documentElement.lang=state.norwegian?'no':'so';
    document.querySelectorAll('[data-so][data-no]').forEach(element=>{element.textContent=localized(element.dataset.so,element.dataset.no)});
    $('cultureLanguage').innerHTML=state.norwegian?'🇸🇴 <span>Af-Soomaali</span>':'🇳🇴 <span>Norsk</span>';
    $('cultureLanguage').setAttribute('aria-label',state.norwegian?'Vis somalisk':'Vis norsk støtte');
    $('cultureTitle').textContent=localized(test.titleSo,test.titleNo);$('cultureSubtitle').textContent=localized(test.subtitleSo,test.subtitleNo);$('cultureThesis').textContent=localized(test.introSo,test.introNo);$('cultureDisclaimer').textContent=localized(test.disclaimerSo,test.disclaimerNo);
    $('cultureStart').firstElementChild.textContent=state.norwegian?'Start testen':'Bilow tijaabada';$('cultureFinish').textContent=state.norwegian?'Se resultatet':'Arag natiijada';
    $('cultureAwardLabel').textContent=state.norwegian?'DIN UTMERKELSE I DAG':'BILADDAADA MAANTA';$('cultureShareHeading').textContent=state.norwegian?'Hvem er neste?':'Yaa ku xiga?';$('cultureShareHelp').textContent=state.norwegian?'Del utmerkelsen, og se hvem i familien eller vennegjengen som får noe helt annet.':'La wadaag biladdaada, kadibna arag qofka qoyska ama saaxiibbada kaa duwan.';
    $('cultureShare').querySelector('b').textContent=state.norwegian?'Del':'La wadaag';$('cultureShareQr').querySelector('b').textContent=state.norwegian?'QR-kode':'QR-koodh';$('cultureDownload').querySelector('b').textContent=state.norwegian?'Lagre kort':'Kaydi kaarka';$('cultureQrTitle').textContent=state.norwegian?'Skann og prøv selv':'Kaamirada ku akhri oo tijaabi';$('cultureQrHelp').textContent=state.norwegian?'La en venn skanne QR-koden for å starte testen.':'Saaxiibkaa ha ku akhriyo QR-koodhka kaamirada taleefankiisa si uu tijaabada u bilaabo.';$('cultureCopyLink').textContent=state.norwegian?'Kopier lenken':'Koobi garee linkiga';
    if(!$('cultureQuestion').classList.contains('hidden'))renderQuestion();
    if(!$('cultureResult').classList.contains('hidden'))renderResult(false);
  }
  function selectVoice(voice,playSample=true){state.voice=voice==='muuse'?'muuse':'ubax';localStorage.setItem('googa-culture-voice',state.voice);document.querySelectorAll('[data-voice]').forEach(button=>{const active=button.dataset.voice===state.voice;button.classList.toggle('active',active);button.setAttribute('aria-checked',active?'true':'false')});if(playSample){const button=document.querySelector(`[data-voice="${state.voice}"]`),text=state.voice==='muuse'?'Waxaan ahay Muuse. Waxaan kuu akhrinayaa Af-Soomaaliga.':'Waxaan ahay Ubax. Waxaan kuu akhrinayaa Af-Soomaaliga.';window.GoogaReadAloud.play(text,'audio/culture-test/voice-sample.mp3',button)}}

  function renderQuestion(){
    const question=test.questions[state.index],category=test.categories[question.category],selected=state.answers[state.index];
    $('cultureProgressLabel').textContent=`${state.index+1} / ${test.questions.length}`;$('cultureProgressFill').style.width=`${(state.index+1)/test.questions.length*100}%`;$('cultureDomainIcon').textContent=category.icon;$('cultureDomainName').textContent=localized(category.so,category.no);$('cultureDomainNo').textContent=state.norwegian?category.so:category.no;
    const questionNumber=String(state.index+1).padStart(2,'0');$('cultureQuestionSo').textContent=localized(question.so,question.no);$('cultureQuestionNo').textContent=state.norwegian?question.so:question.no;$('cultureQuestionNo').classList.add('hidden');$('cultureTranslate').innerHTML=state.norwegian?'🇸🇴 <span>Eeg Af-Soomaali</span>':'🇳🇴 <span>Eeg Af-Noorwiiji</span>';playButton($('cultureQuestionSpeak'),question.so,`audio/culture-test/question-${questionNumber}.mp3`);
    $('cultureScale').innerHTML=question.options.map(option=>`<div class="culture-answer-row"><button class="culture-answer${selected===option.id?' selected':''}" type="button" data-option="${option.id}" aria-pressed="${selected===option.id?'true':'false'}"><i>${option.icon}</i><span><b>${escapeHtml(localized(option.so,option.no))}</b><small>${escapeHtml(state.norwegian?option.so:option.no)}</small></span><em>→</em></button><button class="culture-speak culture-scale-speak" type="button" data-option-speak="${option.id}" aria-label="Dhegeyso jawaabta"></button></div>`).join('');
    $('cultureScale').querySelectorAll('[data-option]').forEach(button=>button.onclick=()=>answer(button.dataset.option));$('cultureScale').querySelectorAll('[data-option-speak]').forEach(button=>{const option=question.options.find(item=>item.id===button.dataset.optionSpeak);playButton(button,option.so,`audio/culture-test/question-${questionNumber}-${option.id}.mp3`)});
    $('cultureFinish').classList.toggle('hidden',state.index!==test.questions.length-1||!selected);
  }
  function answer(optionId){state.answers[state.index]=optionId;if(state.index<test.questions.length-1){state.index++;renderQuestion();window.scrollTo({top:0,behavior:'smooth'})}else renderQuestion()}
  function dimensionScores(answers=state.answers){const totals={norway:0,heritage:0,bridge:0},maxima={norway:0,heritage:0,bridge:0};test.questions.forEach((question,index)=>{const option=question.options.find(item=>item.id===answers[index]);Object.keys(totals).forEach(key=>{totals[key]+=Number(option?.score?.[key]||0);maxima[key]+=Math.max(...question.options.map(item=>Number(item.score?.[key]||0)))})});return Object.fromEntries(Object.keys(totals).map(key=>[key,Math.round(totals[key]/maxima[key]*100)]))}
  function chooseProfile(values){const average=(values.norway+values.heritage+values.bridge)/3;let key='balanced';if(average<35)key='explorer';else if(values.norway>=55&&values.heritage>=55&&values.bridge>=60)key='fusion';else if(values.bridge>=55&&values.bridge>=Math.max(values.norway,values.heritage))key='bridge';else if(values.heritage-values.norway>=15)key='heritage';else if(values.norway-values.heritage>=15)key='norway';return test.profiles.find(profile=>profile.key===key)}

  function renderResult(scroll=true){
    if(state.answers.length!==test.questions.length||state.answers.some(answer=>!answer))return;
    const values=dimensionScores(),profile=chooseProfile(values),axes=Object.entries(test.dimensions).map(([key,dimension])=>({key,...dimension,value:values[key]}));state.result={axes,profile,values};const weakest=axes.slice().sort((a,b)=>a.value-b.value).slice(0,2);
    $('cultureResultIcon').textContent=profile.icon;$('cultureResultTitle').textContent=localized(profile.so,profile.no);$('cultureResultTitleNo').textContent=localized(profile.summarySo,profile.summaryNo);$('cultureResultIntro').textContent=localized(test.resultIntroSo,test.resultIntroNo);playButton($('cultureResultSpeak'),`${profile.so}. ${profile.summarySo}. ${test.resultIntroSo}`,`audio/culture-test/profile-${profile.key}.mp3`);
    $('cultureAxes').innerHTML=axes.map(axis=>`<article style="--score:${axis.value}%"><span class="axis-icon">${axis.icon}</span><div><p><strong>${escapeHtml(localized(axis.so,axis.no))}</strong><b>${axis.value}%</b></p><i><em></em></i><small>${escapeHtml(localized(axis.copySo,axis.copyNo))}</small></div><button class="culture-speak axis-speak" type="button" data-axis="${axis.key}" aria-label="Dhegeyso qaybta"></button></article>`).join('');$('cultureAxes').querySelectorAll('[data-axis]').forEach(button=>{const axis=axes.find(item=>item.key===button.dataset.axis);playButton(button,`${axis.so}. ${axis.copySo}.`,`audio/culture-test/axis-${axis.key}.mp3`)});
    $('cultureActions').innerHTML=weakest.map((axis,index)=>{const action=test.actions[axis.key];return`<article><span>${axis.icon}</span><div><small>${index+1} · ${escapeHtml(localized(axis.so,axis.no))}</small><p>${escapeHtml(localized(action.so,action.no))}</p></div><button class="culture-speak action-speak" type="button" data-action="${axis.key}" aria-label="Dhegeyso tallaabada"></button></article>`}).join('');$('cultureActions').querySelectorAll('[data-action]').forEach(button=>{const action=test.actions[button.dataset.action];playButton(button,action.so,`audio/culture-test/action-${button.dataset.action}.mp3`)});
    $('cultureShareTitle').textContent=profile.so;$('cultureShareAxes').innerHTML=axes.map(axis=>`<div><span>${axis.icon} ${escapeHtml(axis.so)}</span><b>${axis.value}%</b></div>`).join('');show('cultureResult');if(scroll)window.scrollTo({top:0,behavior:'smooth'});
  }

  function wrap(ctx,text,x,y,maxWidth,lineHeight){const words=text.split(' ');let line='';for(const word of words){const trial=line?`${line} ${word}`:word;if(ctx.measureText(trial).width>maxWidth&&line){ctx.fillText(line,x,y);line=word;y+=lineHeight}else line=trial}ctx.fillText(line,x,y)}
  function shareCanvas(){const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d'),gradient=ctx.createLinearGradient(0,0,1080,1350);gradient.addColorStop(0,'#fff1b4');gradient.addColorStop(.55,'#fffaf0');gradient.addColorStop(1,'#bceff0');ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1350);ctx.fillStyle='#123b59';ctx.beginPath();ctx.roundRect(70,70,940,1210,46);ctx.fill();ctx.fillStyle='#e5b84b';ctx.font='900 34px Nunito, sans-serif';ctx.fillText('GOOGA · BARIIS PÅ GRANDIS?!',125,150);ctx.fillStyle='#fff';ctx.font='800 70px Baloo 2, Nunito, sans-serif';wrap(ctx,'Natiijadayda',125,260,820,78);ctx.fillStyle='#bceff0';ctx.font='900 58px Baloo 2, Nunito, sans-serif';wrap(ctx,state.result.profile.so,125,440,820,64);state.result.axes.forEach((axis,index)=>{const y=620+index*150;ctx.fillStyle='#fff';ctx.font='800 30px Nunito';ctx.fillText(`${axis.icon}  ${axis.so}`,125,y);ctx.textAlign='right';ctx.fillText(`${axis.value}%`,945,y);ctx.textAlign='left';ctx.fillStyle='#315d72';ctx.beginPath();ctx.roundRect(125,y+27,820,22,11);ctx.fill();const bar=ctx.createLinearGradient(125,0,945,0);bar.addColorStop(0,'#0ca0a5');bar.addColorStop(1,'#e5b84b');ctx.fillStyle=bar;ctx.beginPath();ctx.roundRect(125,y+27,820*axis.value/100,22,11);ctx.fill()});ctx.fillStyle='#dff5f3';ctx.font='800 27px Nunito';wrap(ctx,'Ma aha inta aad dhab ahaan Soomaali ama Noorwiiji tahay — waa sawirka jawaabahaaga maanta.',125,1110,820,38);ctx.font='46px sans-serif';ctx.fillText('🍚   +   🍕   =   🌉',125,1240);return canvas}
  const cardBlob=()=>new Promise(resolve=>shareCanvas().toBlob(resolve,'image/png',.95));
  async function copyLink(){try{await navigator.clipboard.writeText(shareUrl());shareFeedback(state.norwegian?'Lenken er kopiert.':'Linkiga waa la koobiyeeyey.')}catch(error){const input=document.createElement('textarea');input.value=shareUrl();document.body.appendChild(input);input.select();document.execCommand('copy');input.remove();shareFeedback(state.norwegian?'Lenken er kopiert.':'Linkiga waa la koobiyeeyey.')}}
  async function shareResult(){const blob=await cardBlob(),file=new File([blob],'bariis-pa-grandis.png',{type:'image/png'}),payload={title:'Bariis på Grandis?!',text:shareCopy(),url:shareUrl(),files:[file]};try{if(navigator.canShare?.({files:[file]}))await navigator.share(payload);else if(navigator.share){delete payload.files;await navigator.share(payload)}else await copyLink()}catch(error){if(error.name!=='AbortError')await copyLink()}}
  function shareFacebook(){window.open(channelLinks().facebook,'_blank','noopener,noreferrer,width=680,height=620')}
  function shareEmail(){location.href=channelLinks().email}
  function shareMessage(){location.href=channelLinks().message}
  async function showQr(){const box=$('cultureQrCode');box.innerHTML='';const canvas=document.createElement('canvas');box.appendChild(canvas);await window.QRCode.toCanvas(canvas,shareUrl(),{width:228,margin:1,color:{dark:'#123b59',light:'#ffffff'}});$('cultureQrModal').classList.remove('hidden');document.body.style.overflow='hidden';document.querySelector('.culture-qr-close')?.focus()}
  function hideQr(){$('cultureQrModal').classList.add('hidden');document.body.style.overflow=''}
  async function downloadResult(){const blob=await cardBlob(),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='bariis-pa-grandis.png';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}

  window.GOOGA_CULTURE_TEST_ENGINE={scoreAnswers:answers=>{const values=dimensionScores(answers),profile=chooseProfile(values);return{values,profile:profile.key}},shareLinks:channelLinks};
  $('cultureLanguage').onclick=()=>{state.norwegian=!state.norwegian;updateLanguage()};document.querySelectorAll('[data-voice]').forEach(button=>button.onclick=()=>selectVoice(button.dataset.voice));$('cultureStart').onclick=()=>{state.index=0;state.answers=[];renderQuestion();show('cultureQuestion');window.scrollTo(0,0)};$('cultureBack').onclick=()=>{if(state.index===0)show('cultureIntro');else{state.index--;renderQuestion()}};$('cultureTranslate').onclick=()=>$('cultureQuestionNo').classList.toggle('hidden');$('cultureFinish').onclick=()=>renderResult(true);$('cultureRestart').onclick=()=>{state.index=0;state.answers=[];state.result=null;show('cultureIntro');window.scrollTo(0,0)};$('cultureShare').onclick=shareResult;$('cultureShareFacebook').onclick=shareFacebook;$('cultureShareEmail').onclick=shareEmail;$('cultureShareMessage').onclick=shareMessage;$('cultureShareQr').onclick=showQr;$('cultureCopyLink').onclick=copyLink;$('cultureDownload').onclick=downloadResult;document.querySelectorAll('[data-qr-close]').forEach(button=>button.onclick=hideQr);document.addEventListener('keydown',event=>{if(event.key==='Escape')hideQr()});selectVoice(state.voice,false);updateLanguage();
})();
